os: Visual Studio 2015

platform: x64

environment:
        matrix:
        - test_moar: '2019.03.1'

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - appveyor-retry choco install strawberryperl --version 5.20.1.1 --allow-empty-checksums
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - appveyor DownloadFile "http://rakudo.org/downloads/star/rakudo-star-latest-x86_64 (JIT).msi" -FileName "%APPVEYOR_BUILD_FOLDER%\rakudo.msi"
  - msiexec /i rakudo.msi /quiet /qn /norestart /log install.log
  - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo "installing SSL so we can download the dll files"
  - zef install IO::Socket::SSL
  - zef --depsonly install .
  - zef install Test::META

build: off

test_script:
  - set AUTHOR_TESTING=1 && prove -ve "perl6 -Ilib"
  - zef --debug install .

shallow_clone: true
