name: "Test in a Raku container"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jjmerelo/alpine-raku:gha-2021.10
    steps:
      - name: Test
        run: raku -e 'say $*REPO.repo-chain'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: |
          pwd
          whoami
          which zef
          id `whoami`
          ls -alt /home/raku/.raku
          ls -alt /github/home/.raku
          ls -alt /github/home/raku/.raku
          raku -e 'say $*REPO.repo-chain'
          HOME=/home/raku && raku -e 'say $*REPO.repo-chain' && zef install --verbose --deps-only .

      - name: Test
        run: |
          zef --debug test .


