name: "Test in a Raku container"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jjmerelo/alpine-raku:gha-2021.10
    steps:
      - name: Test
        run: ls -alt /__w
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: |
          pwd
          whoami
          which zef
          id `whoami`
          zef install --deps-only .
          echo $PATH
      - name: Test
        run: |
          zef --debug test .


