name: "Test in a Raku container"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/jj/raku-gha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: |
          raku -e 'say $*REPO.repo-chain'
          which zef
          zef install --verbose --deps-only .

      - name: Test
        run: zef --debug test .


