name: "Test"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jjmerelo/raku-test:latest
      options: --user 1001
    steps:
      - name: Test
        run: |
          whoami
          ls -alt /__w
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: zef install --deps-only .
      - name: Test
        run: zef --debug test .


