name: "Test in a Raku container"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jj/gha-raku:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: |
          raku -e 'say $*REPO.repo-chain'
          HOME=/home/raku && zef install --verbose --deps-only .

      - name: Test
        run: zef --debug test .


